2024-03-07 06:42:18,663 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-03-07 07:10:31,420 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-03-07 07:11:02,419 [WARNING] django.request: Not Found: /
2024-03-07 07:11:29,321 [WARNING] django.request: Not Found: /shop/products/extense
2024-03-07 07:11:29,470 [WARNING] django.request: Not Found: /favicon.ico
2024-03-07 07:22:06,556 [INFO] django.utils.autoreload: /home/alexsky/PycharmProjects/python_django/queries/mysite/mysite/settings.py changed, reloading.
2024-03-07 07:22:08,892 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-03-07 07:27:05,820 [INFO] django.utils.autoreload: /home/alexsky/PycharmProjects/python_django/queries/mysite/mysite/settings.py changed, reloading.
2024-03-07 07:34:17,206 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-03-07 07:34:23,815 [WARNING] django.request: Not Found: /
2024-03-07 07:38:35,869 [INFO] django.utils.autoreload: /home/alexsky/PycharmProjects/python_django/queries/mysite/shopapp/views.py changed, reloading.
2024-03-07 07:38:38,322 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-03-07 07:40:25,019 [INFO] django.utils.autoreload: /home/alexsky/PycharmProjects/python_django/queries/mysite/shopapp/views.py changed, reloading.
2024-03-07 07:40:26,789 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-03-07 07:40:36,999 [WARNING] django.request: Not Found: /
2024-03-07 07:40:58,224 [ERROR] django.request: Internal Server Error: /shop/products/export/
Traceback (most recent call last):
  File "/home/alexsky/PycharmProjects/python_django/queries/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/alexsky/PycharmProjects/python_django/queries/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alexsky/PycharmProjects/python_django/queries/.venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/alexsky/PycharmProjects/python_django/queries/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/alexsky/PycharmProjects/python_django/queries/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/alexsky/PycharmProjects/python_django/queries/mysite/shopapp/views.py", line 145, in get
    name = elem["naem"]
KeyError: 'naem'
2024-03-07 07:43:37,109 [INFO] django.utils.autoreload: /home/alexsky/PycharmProjects/python_django/queries/mysite/shopapp/views.py changed, reloading.
2024-03-07 07:43:38,598 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
